version: '3'
services:
  database_converter_mysql:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: source_database
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
  database_converter_mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: destination_database
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    command: [--auth]
    ports:
      - '27018:27017'
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro